version: '3.5'
services:
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.81.2
    depends_on:
      - "vminsert"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./confs/prometheus-cluster.yml:/etc/prometheus/prometheus.yml
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--promscrape.config=/etc/prometheus/prometheus.yml'
      - '--remoteWrite.url=http://vminsert:8480/insert/0/prometheus/'
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:9.1.0
    depends_on:
      - "vmselect"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
      # load custom dashboards
      - ./provisioning/dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./provisioning/dashboards/vmagent.json:/var/lib/grafana/dashboards/vmagent.json
      - ./provisioning/dashboards/vmalert.json:/var/lib/grafana/dashboards/vmalert.json
      - ./provisioning/dashboards/testdashboard.json:/var/lib/grafana/dashboards/testdashboard.json
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

  vmstorage-1:
    container_name: vmstorage-1
    image: victoriametrics/vmstorage:v1.81.2-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-1:/storage
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--storageDataPath=/storage'
    restart: always

  vmstorage-2:
    container_name: vmstorage-2
    image: victoriametrics/vmstorage:v1.81.2-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-2:/storage
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--storageDataPath=/storage'
    restart: always

  vminsert:
    container_name: vminsert
    image: victoriametrics/vminsert:v1.81.2-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - '--storageNode=vmstorage-1:8400'
      - '--storageNode=vmstorage-2:8400'
    ports:
      - 8480:8480
    restart: always
  vmselect:
    container_name: vmselect
    image: victoriametrics/vmselect:v1.81.2-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - '--storageNode=vmstorage-1:8401'
      - '--storageNode=vmstorage-2:8401'
      - '--vmalert.proxyURL=http://vmalert:8880'
    ports:
      - 8481:8481
    restart: always

  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.81.2
    depends_on:
      - "vmselect"
    ports:
      - 8880:8880
    volumes:
      - ./confs/alerts-cluster.yml:/etc/alerts/alerts.yml
      - ./confs/alerts-health.yml:/etc/alerts/alerts-health.yml
      - ./confs/alerts-vmagent.yml:/etc/alerts/alerts-vmagent.yml
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--datasource.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteRead.url=http://vmselect:8481/select/0/prometheus'
      - '--remoteWrite.url=http://vminsert:8480/insert/0/prometheus'
      - '--notifier.url=http://alertmanager:9093/'
      - '--rule=/etc/alerts/*.yml'
      # display source of alerts in grafana
      - '-external.url=http://127.0.0.1:3000' #grafana outside container
      # when copypaste the line below be aware of '$$' for escaping in '$expr'
      - '--external.alert.source=explore?orgId=1&left=["now-1h","now","VictoriaMetrics",{"expr":"{{$$expr|quotesEscape|crlfEscape|queryEscape}}"},{"mode":"Metrics"},{"ui":[true,true,true,"none"]}]'
    restart: always

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.24.0
    volumes:
      - ./confs/alertmanager.yml:/config/alertmanager.yml
      # force local timezone      
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - '--config.file=/config/alertmanager.yml'
    ports:
      - 9093:9093
    restart: always

volumes:
  vmagentdata: {}
  strgdata-1: {}
  strgdata-2: {}
  grafanadata: {}
